services:
  pyro-server:
    container_name: pyro-server
    build:
      context: ./pyro
    ports:
      - "9090:9090"
    network_mode: host
    
  database-server:
    container_name: server-db
    build: server-db
    volumes:
      - ./server-db:/usr/local/ccf355/server-db
    working_dir: /usr/local/ccf355/server-db
    network_mode: host

  application-server:
    container_name: server-app
    build: server-app
    volumes:
      - ./server-app:/usr/local/ccf355/server-app
    working_dir: /usr/local/ccf355/server-app
    network_mode: host